### Project Name :**Face Recognition based Attendance System**
#### Submitted by,
### **Anna Elizabeth Thambi**
### **September 2022 BigData/DS batch**

I used images of Barak Obama, Lionel Messi, and Sachin Tendulkar to train the recognition model.

So, it's necessary to add pass only these people's images while validating.

In [1]:
import cv2
import numpy as np
import os
from datetime import datetime

In [2]:
def markAttendance(name):
    with open('Attendance.csv', 'r+') as f:
        myDataList = f.readlines()
        nameList = []
        for line in myDataList:
            entry = line.split(',')
            nameList.append(entry[0])
        if name not in nameList:
            time_now = datetime.now()
            tString = time_now.strftime('%H:%M:%S')
            dString = time_now.strftime('%d/%m/%Y')
            f.writelines(f'\n{name},{tString},{dString}')

In [3]:
def name_map(x):
    if x=='Messi':
        return 0
    if x=='Obama':
        return 1
    if x=='Sachin':
        return 2
   

In [4]:
def get_name(x):
    if x==0:
        return 'Messi'
    if x==1:
        return 'Obama'
    if x==2:
        return 'Sachin'

In [5]:
def detect_face(img):
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    face_cascade =cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
    faces =face_cascade.detectMultiScale(gray,scaleFactor=1.1,minNeighbors=4,minSize=(30,30))

    if(len(faces)==0):
        return None,None # if there is no face to detect
    (x,y,w,h) = faces[0] # first element in faces[]
    
    return gray[y:y+w,x:x+h] ,faces[0] # to crop the image


In [6]:
dirs=os.listdir('data')
classnames = dirs
print(classnames)

['Messi', 'Sachin', 'Obama']


In [7]:
for dir_name in dirs:

    subject_dir_path ='data' + '/' + dir_name    
    subject_img_names=os.listdir(subject_dir_path)

    for img_names in subject_img_names:
        img_path=subject_dir_path+'/' +img_names
        print(img_path)

data/Messi/02.jpg
data/Messi/05.jpg
data/Messi/03.jpg
data/Messi/06.jpg
data/Messi/07.jpg
data/Messi/10.jpg
data/Messi/04.jpg
data/Messi/09.jpg
data/Messi/01.jpg
data/Messi/08.jpg
data/Sachin/02.jpg
data/Sachin/05.jpg
data/Sachin/03.jpg
data/Sachin/06.jpg
data/Sachin/07.jpg
data/Sachin/10.jpg
data/Sachin/04.jpg
data/Sachin/09.jpg
data/Sachin/01.jpg
data/Sachin/08.jpg
data/Obama/02.jpg
data/Obama/05.jpg
data/Obama/03.jpg
data/Obama/06.jpg
data/Obama/07.jpg
data/Obama/10.jpg
data/Obama/04.jpg
data/Obama/09.jpg
data/Obama/01.jpg
data/Obama/08.jpg


In [8]:
def prepare_training_data(data_folder_path):
    dirs=os.listdir(data_folder_path)

    faces= []
    labels= []
    
    for dir_name in dirs:

        label=dir_name

        subject_dir_path = data_folder_path+'/' +dir_name
        subject_img_names =os.listdir(subject_dir_path)

        for img_name in subject_img_names:
            img_path = subject_dir_path+'/'+img_name

            image=cv2.imread(img_path)
            cv2.imshow('prepare_training_data...',image)
            cv2.waitKey(1000)
                

            face,rect=detect_face(image)

            if face is not None:
                faces.append(face)
                labels.append(name_map(label))
                print(labels)
    cv2.waitKey(1)
    cv2.destroyAllWindows()

    return faces ,labels
            

In [9]:
print('preparing data')

faces , labels=prepare_training_data('data')

print('data prepared')

preparing data
[0]
[0, 0]
[0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 

In [10]:
print('total faces',len(faces))

total faces 29


In [11]:
print('total labels',len(labels))

total labels 29


In [12]:
face_recognizer = cv2.face.LBPHFaceRecognizer_create()

In [13]:
face_recognizer.train(faces,np.array(labels))

In [14]:
def draw_rectangle(img,rect):

    (x,y,w,h)=rect
    cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),3)


In [15]:
def draw_text(img,text,x,y):
    cv2.putText(img,text,(x,y),cv2.FONT_HERSHEY_SCRIPT_COMPLEX,1,(0,0,255),2)
    markAttendance(text)

In [16]:


def predict(test_img):
    img = test_img.copy()
    
    face,rect=detect_face(img)
    x,y= rect[0],rect[1]

    label = face_recognizer.predict(face)
    
    label_text = get_name(label[0])
    
    draw_rectangle(img,rect)

    draw_text(img,label_text,rect[0],rect[1])

    return img


In [17]:
import cv2 

key = cv2. waitKey(1)
webcam = cv2.VideoCapture(0)
while True:
    try:
        check, frame = webcam.read()
        print(check) #prints true as long as the webcam is running
        print(frame) #prints matrix values of each framecd 
        cv2.imshow("Capturing", frame)
        key = cv2.waitKey(1)
        if key == ord('s'): 
            cv2.imwrite(filename='saved_img.jpg', img=frame)
            webcam.release()
            img_new = cv2.imread('saved_img.jpg', cv2.IMREAD_GRAYSCALE)
            img_new = cv2.imshow("Captured Image", img_new)
            cv2.waitKey(1650)
            cv2.destroyAllWindows()
            print("Processing image...")
            img_ = cv2.imread('saved_img.jpg', cv2.IMREAD_ANYCOLOR)
            print("Converting RGB image to grayscale...")
            gray = cv2.cvtColor(img_, cv2.COLOR_BGR2GRAY)
            print("Converted RGB image to grayscale...")
            print("Resizing image to 28x28 scale...")
            img_ = cv2.resize(gray,(50,50))
            print("Resized...")
            img_resized = cv2.imwrite(filename='saved_img-final.jpg', img=img_)
            print("Image saved!")
        
            break
        elif key == ord('q'):
            print("Turning off camera.")
            webcam.release()
            print("Camera off.")
            print("Program ended.")
            cv2.destroyAllWindows()
            break
        
    except(KeyboardInterrupt):
        print("Turning off camera.")
        webcam.release()
        print("Camera off.")
        print("Program ended.")
        cv2.destroyAllWindows()
        break

True
[[[  0   1  10]
  [  0   1  10]
  [  0   0   6]
  ...
  [188 213 215]
  [188 216 213]
  [181 209 206]]

 [[  0   3   4]
  [  0   4   5]
  [  0   0   6]
  ...
  [190 215 213]
  [190 215 213]
  [188 214 212]]

 [[  0   0   6]
  [  0   0   6]
  [  0   1   7]
  ...
  [190 215 213]
  [190 215 213]
  [190 215 213]]

 ...

 [[  0   2   1]
  [  0   2   1]
  [  0   3   2]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[  0   2   1]
  [  0   2   1]
  [  0   2   1]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[  0   1   0]
  [  0   1   0]
  [  0   2   1]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
True
[[[  3   3   3]
  [  5   5   5]
  [  2   2   2]
  ...
  [196 213 217]
  [195 213 212]
  [196 214 213]]

 [[  3   3   3]
  [  2   2   2]
  [  0   2   1]
  ...
  [200 211 218]
  [195 211 215]
  [200 217 221]]

 [[  2   2   2]
  [  1   1   1]
  [  0   2   1]
  ...
  [200 211 218]
  [192 208 215]
  [193 209 216]]

 ...

 [[  0   3   5]
  [  0   2   4]
  [  0   3

In [18]:
test_img1 = cv2.imread("saved_img.jpg")
predcted=predict(test_img1)
cv2.imshow('predcted img',predcted)
cv2.waitKey(5000)
cv2.destroyAllWindows()